### ISSUE TITLE
Server key faulty when using action on ubuntu-latest

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/action-release-with-hemtt#10]
I updated `grad_slingHelmet` yesterday and immediately got reports that the server key is broken. After some investigation I found out that, this seems to happen, when the action runs on `ubuntu-latest`. Everything works fine on `windows-latest`.

See the following two action runs:
- [Ubuntu](https://github.com/gruppe-adler/grad_slingHelmet/actions/runs/966293623)
- [Windows](https://github.com/gruppe-adler/grad_slingHelmet/actions/runs/966298773)

_You can download both artifacts and check with DS Utils yourself_

Ubuntu:
![](https://i.imgur.com/dRGyWRc.png)

Windows:
![](https://i.imgur.com/JUdvPLZ.png)

---

I know this is probably an issue with HEMTT itself, but I'm way to tired to figure that shit out so I'll post an issue here and hope someone has the knowledge and time to investigate further.

**Comment by Fusselwurm** [comment]
https://github.com/BrettMayson/HEMTT/issues/278

**Comment by DerZade** [comment]
I see. In my opinion we should at least add a warning or something in stdout and README as long as we use a „broken“ version of HEMTT.
